parameters:
    app.name: '%env(resolve:APP_NAME)%'
    app.version: '%env(APP_VERSION)%'

    target.currency: '%env(TARGET_CURRENCY)%'
    countries.collection: '%env(json:COUNTRIES_COLLECTION)%'
    in.collection.multiplier: '%env(IN_COLLECTION_MULTIPLIER)%'
    not.in.collection.multiplier: '%env(NOT_IN_COLLECTION_MULTIPLIER)%'

    rates.provider.api.key: '%env(RATES_PROVIDER_API_KEY)%'
    rates.provider.endpoint.url: '%env(RATES_PROVIDER_ENDPOINT_URL)%'

    bin.to.country.provider.endpoint.url: '%env(BIN_TO_COUNTRY_PROVIDER_ENDPOINT_URL)%'
